### ISSUE TITLE
Attribute design sheet pages - menu attributes missing

### ISSUE THREAD

**Issue by wrijpkema** [LivePersonInc/developer-center#1098]
Attribute design sheet pages for neither iOS nor Android contain any visualisation nor description of available attributes in the action menu ('Mark as urgent'; 'Clear history' and 'Mark as resolved'). Could these please be added to https://developers.liveperson.com/mobile-app-messaging-sdk-for-ios-sdk-attributes-attributes-design-sheet.html and https://developers.liveperson.com/mobile-app-messaging-sdk-for-android-sdk-attributes-attributes-design-sheet.html?

**Comment by j9t** [comment]
Thanks for bringing this up, @wrijpkema, and the patience! @itay1313, could you have a look?

**Comment by j9t** [comment]
(Followed up on this again internally.)

**Comment by j9t** [comment]
This is going to handled in MBK-2822. Closing this issue to avoid duplicates; re-open if there are any questions.

**Comment by wrijpkema** [comment]
Hi @j9t , would you mind sharing a link to MBK-2822 so I may track the progress on this one? TIA!
