### ISSUE TITLE
Issue with Reporting -> Personal Data Deletion API -> Methods -> Create Deletion Request

### ISSUE THREAD

**Issue by amirmLP** [LivePersonInc/developer-center#1099]
Under [this](https://developers.liveperson.com/personal-data-deletion-api-methods-create-deletion-request.html) article, it states the following:
consumerId - deletion of personal data that is related to a specific consumer (does not include the consumer's conversations; those must be deleted in a separate request). Note: in other APIs, the consumerId is referred to as visitorId (for example, the Engagement History API). You can use that visitorId as part of this request to identify the specific visitor for which you'd like to request data deletion.

------------------------

The consumerId is an identifier created by UMS to identify a consumer participant in messaging conversations.
The visitorId is an identifier created by Shark to identify a monitored visitor in monitoring sessions (whether on the web or via the monitoring API in mobile apps).

They are two very different identifiers for different entities on different systems.
The API mentioned there (the engagement history API) is for Chat only, not for messaging.

The above is very confusing and should be amended.

**Comment by j9t** [comment]
@amirmLP, thanks for the patience and for sharing this! Would you be open to filing a PR for this update, while we’re getting on top of all open issues? That would be super-helpful. (Thank you!)

**Comment by j9t** [comment]
(Followed up with the respective team.)

**Comment by amirmLP** [comment]
Hi @j9t ,
I won't have the time to raise PRs for these issues but I'm happy to write a draft for the text that needs changing:
3. consumerId: Deletion of personal data that is related to a specific consumer (does not include the consumer's conversations; those must be deleted in a separate request). Note: In the Messaging Interactions API, the consumerId is referred to as "participantId" under the "consumerParticipants" array. You can use that participantId as part of this request to identify the specific consumer for which you'd like to request data deletion.

**Comment by j9t** [comment]
Thanks Amir! I followed up on this again internally.

**Comment by j9t** [comment]
Should be fixed now, thanks to @martincm1’s PR #1947!
