### ISSUE TITLE
Specify ABC List Picker requirements

### ISSUE THREAD

**Issue by wrijpkema** [LivePersonInc/developer-center#1212]
The link offered under https://developer.apple.com/documentation/businesschatapi/messages_sent/interactive_messages/list_picker
in regards to the List Picker interaction having "been developed per Apple's List Picker specifications" links to a page which mentions little specifications (https://developer.apple.com/documentation/businesschatapi/messages_sent/interactive_messages/list_picker); e.g. image resolution guidelines are not mentioned there.

Suggestion to either link to https://developer.apple.com/design/human-interface-guidelines/business-chat/interactive-messages/pickers/ and/or to mention the guidance around e.g. image resolution stated there.

**Comment by j9t** [comment]
@wrijpkema, thanks for sharing this as well as the patience. Does the issue still persist? We would need to check with the teams on changes to the docs or other useful references.

**Comment by wrijpkema** [comment]
@j9t , as far as I can see, https://developers.liveperson.com/apple-messages-for-business-templates-list-picker-template.html#body---overview and following sections contain more of the relevant specs and guidelines; I can't find a reference to Apple's Developer site at all anymore, though. As e.g. image resolution guidelines still are not listed under https://developers.liveperson.com/apple-messages-for-business-templates-list-picker-template.html#body---list-picker-items, I would still suggest to either link to https://developer.apple.com/design/human-interface-guidelines/business-chat/interactive-messages/pickers/ and/or to mention the guidance around e.g. size limits / image resolution stated there.

**Comment by j9t** [comment]
Thanks @wrijpkema!

@itay1313, could you have a look and tweak our docs? (We can keep it light and take note, to have the respective team check again.) Thanks!

**Comment by mferreira-lp** [comment]
Hi All,

I’m working on updates per this issue to the following pages:
https://developers.liveperson.com/conversation-builder-interactions-questions.html#apple-list-picker
https://developers.liveperson.com/conversation-builder-interactions-questions.html#apple-time-picker
https://developers.liveperson.com/conversation-builder-interactions-integrations.html#apple-pay-interactions
I’m “folding in”  these changes into the doc updates for the next release of Conversation Builder+. 

For any update to
https://developers.liveperson.com/apple-messages-for-business-templates-list-picker-template.html
…you’ll need to contact another team, as I’m not familiar with this area. If an update here is not required, you can reassign this issue to me, and I will close it when the CB+ docs are published.

Thank you.

**Comment by j9t** [comment]
Late thanks, @mferreira-lp! Unless I misunderstood, feeling free to assign to you.

**Comment by mferreira-lp** [comment]
Hi @j9t, yes, certainly - You can assign it to me for the fixes to the Conversation Builder docs. I'll need to reassign it to another to take care of any changes to 
https://developers.liveperson.com/apple-messages-for-business-templates-list-picker-template.html. Thank you!

**Comment by j9t** [comment]
(Followed up on this again internally.)

**Comment by mferreira-lp** [comment]
This item has been logged internally as BA-13093. cc @wrijpkema, @j9t

**Comment by j9t** [comment]
Thank you! (Closing this one.)
