### ISSUE TITLE
Remove "MessagingFailover" and "LiveEngageMMSViewer" permalinks

### ISSUE THREAD

**Issue by cjames1224** [LivePersonInc/developer-center#1218]
We need to remove the following pages from the developer community, as the solutions are not supported by me or anyone else. These pages are still searchable from Google and can cause confusion for our customers.

https://github.com/LivePersonInc/developers-community/tree/master/pages/Documents/Solutions/MessagingFailover
https://github.com/LivePersonInc/developers-community/tree/master/pages/Documents/Solutions/LiveEngageMMSViewer

**Comment by cjames1224** [comment]
> We need to remove the following pages from the developer community, as the solutions are not supported by me or anyone else. These pages are still searchable from Google and can cause confusion for our customers.
> 
> https://github.com/LivePersonInc/developers-community/tree/master/pages/Documents/Solutions/MessagingFailover
> https://github.com/LivePersonInc/developers-community/tree/master/pages/Documents/Solutions/LiveEngageMMSViewer

@EdenKupe

**Comment by j9t** [comment]
@lkisoslive and I have been cleaning up; the whole “Solutions” section had been a duplicate, which we resolved; we’ll be marking other pages as “deprecated” shortly (handled in a separate issue internally).

Thanks for reporting this, @cjames1224!
