### ISSUE TITLE
List of limitations of Proactive Messaging to in app is missing all but one limit

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developer-center#1300]
[Proactive and IVR Deflection to App Messaging](https://developers.liveperson.com/mobile-app-messaging-sdk-for-ios-advanced-features-proactive-and-ivr-deflection-to-app-messaging.html#limitation)

There is only one limitation listed, however, there are actually far more. The limitations are not captured here, or in the (Proactive API Documentation)[https://developers.liveperson.com/proactive-messaging-api.html]

![image](https://user-images.githubusercontent.com/25583661/117272961-94fc1880-ae53-11eb-8cbc-9ee9b4ae0709.png)

**Comment by lp-tattwell** [comment]
Hey Jens, I'm unsure how many of these limitations are still relevant. The product has come a fair bit along since May 2021.

Can we get the product owner involved to validate and to create the PR?

**Comment by j9t** [comment]
Let me see if I can identify a contact.

**Comment by j9t** [comment]
(No feedback yet, but have reminded the team again.)

**Comment by j9t** [comment]
(Followed up on this again internally.)

**Comment by j9t** [comment]
This is going to handled in MBK-2821. Closing this issue to avoid duplicates; re-open if there are any questions.
