### ISSUE TITLE
[iOS] M1 Support for XCFramework 

### ISSUE THREAD

**Issue by mstana** [LivePersonInc/developer-center#1567]
Hello, 

I would like to ask you if you plan to support M1 architecture for simulators in XCFramework in https://github.com/LP-Messaging/iOS-Messaging-SDK.

Currently, the pod which is built does not support arm64 for a simulator which will limit us in the future to use this SDK with M1 chips natively on new MacBooks. 

Thanks

**Comment by j9t** [comment]
@dvillacis94, it seems you’re a main contributor to the iOS Messaging SDK. Can you advise?

**Comment by ppalraj-lp** [comment]
The support for the M1 chip is planned for the 9/3 release. I will update here if there is any change in the plan. thanks.

**Comment by j9t** [comment]
This is going to handled in MBK-2823. Closing this issue to avoid duplicates; re-open if there are any questions.
