### ISSUE TITLE
Rename Apple Business Chat

### ISSUE THREAD

**Issue by cshort-lp** [LivePersonInc/developer-center#1581]
The following find and replace actions need to take place:

Apple Business Chat -> ﻿Apple Messages for Business
﻿Business Chat -> ﻿Messages for Business
ABC -> AMB

**Note**: move `permalink` to the `redirects` before changing `pagename`

**Comment by itay1313** [comment]
@cshort-lp  Cale, could you please file a PR? Please let me know if you are interested in helping me with this. Since I see it everywhere, it seems too dangerous.

**Comment by j9t** [comment]
@cshort-lp and I briefly chatted about this, and Cale would not be able to help further. On the plus side, several instances of this were apparently updated already.

Will follow up internally to decide on next steps.

**Comment by lkisoslive** [comment]
Created DX-128 to follow up on this.

**Comment by j9t** [comment]
(Now handled in CX-5740 and CC-4187.)
