### ISSUE TITLE
Users API overview mistake

### ISSUE THREAD

**Issue by amirmLP** [LivePersonInc/developer-center#1664]
The users API's overview page (https://developers.liveperson.com/users-api-overview.html) has this text:
"Automatically update user information such as profile picture, login name, or password"

The login name is a protected field that cannot be changed once set at point of a user's creation.

**Comment by j9t** [comment]
(Followed up internally.)

**Comment by j9t** [comment]
(No response yet; keeping at it.)

**Comment by j9t** [comment]
(Followed up on this again internally.)

**Comment by lpbarber** [comment]
fixed.
