### ISSUE TITLE
Agent Escalation Integration transfer details need to be updated

### ISSUE THREAD

**Issue by theharlotfelon** [LivePersonInc/developer-center#1737]
In the article [LivePerson Agent Escalation Integrations](https://developers.liveperson.com/conversation-builder-integrations-liveperson-agent-escalation-integrations.html), the Agent ID (optional) section of the setup states "Transfer of the conversation to this agent ID only occurs if the agent is assigned to the skill ID that you specify and is available". 

From an API perspective, it is not checking for availability for the user as it will transfer to the agent with permission "SUGGESTED_ASSIGNED_AGENT" and if the agent accepts it, they then are set with the permission "ASSIGNED_AGENT".  If the agent does not accept this (for whatever reason), then another transfer event occurs where it is sent to the same skill queue. 

From a UI perspective, it follows what is detailed in the knowledge center in the article [Transfer to agent
](https://knowledge.liveperson.com/contact-center-management-messaging-operations-transfer-to-agent.html#Viewing%20transferred%20conversations%20in%20the%20All%20Conversations%20tab). Threshold time for agent transfers is set in ACD configuration in Night Vision.

**Comment by j9t** [comment]
Thanks @theharlotfelon! I know this requires some extra effort, but would you be open to filing a PR for this, for an update?

We’re working on the site with a new team and can use every hand to speed things up. Thank you!

**Comment by j9t** [comment]
(Followed up internally.)

**Comment by j9t** [comment]
(Followed up on this again internally.)

**Comment by mferreira-lp** [comment]
This issue has been logged internally as BA-13094. cc @theharlotfelon, @j9t

**Comment by j9t** [comment]
Thank you! (Closing this one.)
