### ISSUE TITLE
Incorrect URL given in API Authorization under the Conversation Orchestrator Section

### ISSUE THREAD

**Issue by ktse123** [LivePersonInc/developer-center#1863]
When guiding you through how to generate API Authorization for V2 step 2 Generate your OAuth 2.0 secure access token using the credentials.  A URL is given have tried to test this myself and get a 404 not found. Looking through slack i found a post that stated this URL is wrong but information fr the correct one is not given 
[snip]
![Screenshot 2022-09-05 at 11 49 50](https://user-images.githubusercontent.com/109209700/188432132-ed0dcfb7-7688-4c2b-a162-48a3909e7311.png)

**Comment by j9t** [comment]
@ktse123, happy to look into that with you. Could you follow up with me internally (Slack preferred)?

**Comment by j9t** [comment]
Per our conversation, this is related to https://developers.liveperson.com/conversation-orchestrator-api-authorization.html and the URL given with “https://{domain}/v2/authenticate/login”, which doesn’t work.

@mferreira-lp, as this seems to relate to your and team’s docs, can you help update this information?

**Comment by mferreira-lp** [comment]
Hi @ktse123 , we received this same inquiry mid last week via the Feedback tool. Not sure if that was you, but thank you for raising this. I followed up on this last Thursday with the team and waiting to hear back before responding. Thanks again. cc @j9t

**Comment by lkisoslive** [comment]
Thank you for bringing this to our attention @ktse123 and Mary for the PR. @ktse123 can you confirm that it is working after the update? Thanks!
