### ISSUE TITLE
Automatic messages documentation inaccurate

### ISSUE THREAD

**Issue by amirmLP** [LivePersonInc/developer-center#361]
There are 2 types of auto messages:
1) Auto messages for Chat:
https://developers.liveperson.com/automatic-messages-api-overview.html
2) Auto messages for Messaging (unified auto messages):
https://developers.liveperson.com/unified-automatic-messages-api-overview.html

The documentation on both of those APIs says that they cover both Chat and Messaging.
Additionally, the documentation itself (on both of them) has the following issues (and possibly more):
1) Does not include necessary information such as the "view" param not having the allowed values in it.
2) The chat auto messages get all method has no information about the various params that can be used in it.
3) The update method in both APIs (+ the delete method in the messaging one) is incorrect. It shows the method as PUT or DELETE where the API only accepts GET, POST or PATCH. The X-HTTP-Method-Override header is used to override POST to PUT or DELETE. On the DELETE page, the explanation of the X-HTTP-Method-Override header says it should be changed to PUT when it obviously should be DELETE.

**Comment by EdenKupe** [comment]
Opened a ticket for the relevant owner. Will close this issue when the docs are updated.

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)

**Comment by amirmLP** [comment]
Hi @j9t , sorry for the delay. I'm finally getting through my backlog to these requests.
Yes, the issues detailed above are still present in the documentation and still need fixing.

**Comment by j9t** [comment]
Thanks for confirming, @amirmLP. I followed up with the respective team.

**Comment by j9t** [comment]
(Followed up again internally.)

**Comment by j9t** [comment]
The respective team is going to work on this—we’ll track this internally (CAO-21939).
