### ISSUE TITLE
Code flow listed twice under different names

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developer-center#377]
In the auth docs, it lists "Code Flow" and "OAuth 2.0 code" as two separate flows we support. They are the same thing so they should be merged or one removed.

![image](https://user-images.githubusercontent.com/25583661/62955295-b1873000-bde8-11e9-83a4-c1fc4ed55549.png)

**Comment by lp-tattwell** [comment]
in this page https://developers.liveperson.com/mobile-sdk-and-web-authentication-introduction.html

**Comment by trosel** [comment]
@lp-tattwell where is the issue on the page? I just see a section that lists terminology 

<img width="904" alt="image" src="https://user-images.githubusercontent.com/1299322/63025719-cc54b580-be77-11e9-9e5b-1fbd3b3bf995.png">

**Comment by lp-tattwell** [comment]
In the auth docs, it lists "Code Flow" and "OAuth 2.0 code" as two separate flows we support. They are the same thing

**Comment by EdenKupe** [comment]
Isn't code flow mentioning a more general use case, with OAuth just being one example? That's how I understand the text, that some flows provide a code and OAuth is just one of them.

**Comment by lp-tattwell** [comment]
OAuth is the framework/protocol (whatever you want to call it) and Implicit Flow and Code Flow are implementations of that framework.

The information in both is valid so I think they just need merging together rather than one being removed outright in favour of the other.

**Comment by EdenKupe** [comment]
Got it. @lpbarber can you take a look?

**Comment by trosel** [comment]
@lp-tattwell If it's not clear, that's just a list of vocabulary words. It's just terms with definitions. 

I suppose it could use some editing to be more useful. I mean, the website is written for developers, so they should know what OAuth2 is already.

**Comment by peterswimm** [comment]
Fwiw for things that should be obvious to most people, We could just link the term to some public discussion of what it is for the 1% that needs it. This can be like the Wikipedia entry or whatever. We don't have to own the curation of describing it but it just a useful something for someone.

**Comment by j9t** [comment]
Hi @lp-tattwell, @trosel, @EdenKupe—is this still relevant, was there any work done on this?

**Comment by lp-tattwell** [comment]
Hey Jens, the page has moved but the information is the same as it was in 2019.
https://developers.liveperson.com/consumer-authentication-introduction.html

I'm not saying it's a major P0 issue but listing the same thing twice with 2 different descriptions is a little confusing, especially on a complicated topic.

**Comment by j9t** [comment]
I’ll look into it.

**Comment by j9t** [comment]
@lp-tattwell, reviewing the doc and this thread I pick up the doc isn’t precise, but I’m not reading the information as two separate flows we’d support.

Do you have a suggestion on specific things to change? (If not a PR, maybe as a comment here?) That would be helpful.

(We’re looking into gathering contacts for each section of the site, but at the moment we have no easy way of looping in people from the respective teams working on each topic.)

**Comment by j9t** [comment]
(Setting up a redirect from past https://developers.liveperson.com/mobile-sdk-and-web-authentication-introduction.html to https://developers.liveperson.com/consumer-authentication-introduction.html.)

**Comment by j9t** [comment]
@lpbarber, it seems you’ve been involved with this in the past, and own this documentation; can you review and update this part of https://developers.liveperson.com/consumer-authentication-introduction.html?

**Comment by j9t** [comment]
(Followed up again internally.)

**Comment by lpbarber** [comment]
@j9t - I'm not what is expected me to do here, as I can not see, and not familiar with the "Past" (mobile-sdk-and-web-authentication-introduction.html) page

**Comment by j9t** [comment]
Hi @lpbarber—you’re marked as the owner of this documentation and you’ve also [edited the respective page](https://github.com/LivePersonInc/developer-center/commits/master/pages/Documents/Security%26Authentication/ConsumerAuthentication/introduction.md) in the past.

Timothy (and Eden, if I understand correctly) suggest to review and consolidate the documentation. Could you do that?

If you disagree and find it to be sufficient for the audience, on the DX/DC side I don’t think we would challenge this right now—so feel free to share your take and close the issue, too.

(Furthermore, we can also follow up and coordinate internally, if that can help.)

**Comment by lpbarber** [comment]
@j9t - I have reviewed the documentation once again and I don't find a real issue here.
we can review it together if you would like or close the issue.

**Comment by j9t** [comment]
If you reviewed and there’s no issue, all cool—thanks @lpbarber!

@lp-tattwell, feel free to reach out internally if there’s something left open, or if you feel strongly about something here. Closing this in the meantime.
