### ISSUE TITLE
messaging-agent-sdk documentation gaps

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developer-center#495]
https://developers.liveperson.com/messaging-agent-sdk-overview.html

1) How to unsubscribe from events is missing. dispose() is listed, however, it isn't described when this should be called. unsubscribeExConversations is a method available to the SDK but is not documented anywhere publicly.
2) Reconnect with skipTokenGeneration isn't explained. i don't know when or why I would ever skip the generation.
3) For most cases, dialog Id matches conv Id. When does dialog Id change (survey bot)?
4) In terms of reconnection, if a bot disconnects, reconnects successfully and then immediately disconnects, the bot will spam LP with reconnection attempts. This should be accounted for in our reconnect best practises.

**Comment by EdenKupe** [comment]
Sent to the relevant owner.

**Comment by lp-tattwell** [comment]
@EdenKupe Who is the relevant owner? It would be useful to get the answers now if it is going to take time to get the documentation updated.

**Comment by EdenKupe** [comment]
Added you to a follow up

**Comment by j9t** [comment]
@lp-tattwell, @EdenKupe, is this still relevant? Was there work done on this?

**Comment by lp-tattwell** [comment]
```1. How to unsubscribe from events is missing. dispose() is listed, however, it isn't described when this should be called. unsubscribeExConversations is a method available to the SDK but is not documented anywhere publicly.```

- Dispose has a description [HERE](https://developers.liveperson.com/messaging-agent-sdk-methods.html#dispose) but it doesn't explain when or what scenario it should be used
- unsubscribeExConversations is still undocumented

```2. Reconnect with skipTokenGeneration isn't explained. i don't know when or why I would ever skip the generation.```

- The flag is commented on [HERE](https://developers.liveperson.com/messaging-agent-sdk-methods.html#reconnectskiptokengeneration) and I can infer what it's for but it's not explicitly stated what it's for or what it does and why.

```3. For most cases, dialog Id matches conv Id. When does dialog Id change (survey bot)?```

- In all of the code examples (See [HERE](https://developers.liveperson.com/messaging-agent-sdk-methods.html#updateconversationfield) for example), the conversationId field is populated by`conversationId/dialogId`. It is not explained when to use the conversationId and when to use the dialogId.
  - I believe there are two keys available now, where you can actually pass the `conversationId` and `dialogId` separately, instead of alternating between the two in some secret scenario
  - The one use case where dialogId changes is documented [HERE](https://developers.liveperson.com/messaging-agent-sdk-methods.html#example-close-dialog) halfway down the page. It's not clear how this links to the `conversationId/dialogId` fields in any of the other examples.

```4. In terms of reconnection, if a bot disconnects, reconnects successfully and then immediately disconnects, the bot will spam LP with reconnection attempts. This should be accounted for in our reconnect best practises.```

- Is now resolved.

**Comment by j9t** [comment]
Thanks @lp-tattwell! @itay1313, can you help update the docs? Happy to work with you to pinpoint internal contacts.

**Comment by j9t** [comment]
@lkisoslive, not urgent—could you have a look at this?

**Comment by j9t** [comment]
(Following up again internally.)

**Comment by lkisoslive** [comment]
Filed DX-133 to follow up on this with the relevant team (CXS Thunderbirds)
