### ISSUE TITLE
Connector Api assigned_agent id

### ISSUE THREAD

**Issue by borisromanov** [LivePersonInc/developer-center#657]
From working with the Connector API, I've noticed that there is no way to map the `id` of the `ASSIGNED_AGENT` from this example back to an Chat Agent in the LivePerson workspace.
```
{
 "kind": "notification",
 "body": {
  "changes": [
   {
    "type": "UPSERT",
    "result": {
     "convId": "5491244f-e462-4c63-bf4e-faf4b2d3e7b5",
     "conversationDetails": {
      "participants": [
       {
        "id": "29c3019d-fe0b-5200-afe8-737abfeae4b4",
        "role": "ASSIGNED_AGENT"
       },
       {
        "id": "ade26082b1185839d17e0794924c1a0005cf5663e7c35e38f80dd8552a1a96e5",
        "role": "CONSUMER"
       }
      ],
      "brandId": "64467156",
      "state": "OPEN",
      "startTs": 1528371161882,
      "metaDataLastUpdateTs": 1528371195521,
      "ttr": {
       "ttrType": "PRIORITIZED",
       "value": 600
      }
     }
    }
   }
  ]
 },
 "type": "cqm.ExConversationChangeNotification"
}
```
https://developers.liveperson.com/connector-api-webhooks-webhooks-examples.html#agent-assigned-to-the-conversation

**Comment by elliotmassen** [comment]
@j9t I'm also searching for an answer to this question. I'd like to be able to map the Assigned Agent's ID to a User ID, so I can make use of the [User API](https://developers.liveperson.com/users-api-methods-get-user-by-id.html).

**Comment by j9t** [comment]
Thanks @elliotmassen. We’re looking into it (will try to monitor, but also rely on other contacts).

**Comment by borisromanov** [comment]
Hi @j9t, thanks for reaching out. Is there anywhere an assigned participants id can be looked up in a separate LivePerson API and return more generic information about an assigned agent?

I have a use case where I use data from the Connector API in realtime and would like to augment that data stream with information about the assigned agent.

**Comment by j9t** [comment]
Let’s find out—I’ve contacted the team providing the API to follow up.

**Comment by j9t** [comment]
(No response yet—keeping at it.)

**Comment by jasmith-lp** [comment]
Hi @borisromanov Participant ID comes back when you query the Users API

https://developers.liveperson.com/users-api-appendix.html
It is under the field PID (the example payload is not 100% representative of a real participantID)

**Comment by j9t** [comment]
Pardon me just scanning as I’m reviewing all open issues—did this help, @borisromanov?

**Comment by j9t** [comment]
The respective team is looking into this (CO-5761). I’ll be closing this one for now, but will raise with the team to share an update here if possible.
