### ISSUE TITLE
Rate limitting needs to be included

### ISSUE THREAD

**Issue by igor-liveperson** [LivePersonInc/developer-center#799]
https://developers.liveperson.com/api-guidelines-retry-policy-recommendations.html

we need to include more details on 429 in a single place. This indicates 4xx is a "do not retry" and this needs to be aligned with the fact that 429 is an instance when we want them to retry. Ideally listing all APIs or services that are affected.

**Comment by j9t** [comment]
(Closing this because of seemingly small problem and lack of feedback and contacts.)
